export const States = [
  {
    name: "Andhra-pradesh",
    id: "1",
    details:
      `Andhra Pradesh is a state in the south-eastern coastal region of India. It is the seventh-largest state by area covering an area of 162,975 km² and tenth-most populous state with 49,386,799 inhabitants.It is bordered by Telangana to the north-west, Chhattisgarh to the north, Odisha to the north-east, Tamil Nadu to the south, Karnataka to the west and the Bay of Bengal to the east. It has the second longest coastline in India after Gujarat, of about 974 km (605 mi). Andhra Pradesh is the first state to be formed on a linguistic basis in India on 1 October 1953. Andhra Pradesh was once a major Buddhist pilgrimage site in India and a Buddhist learning center which can be seen in many sites in the state in the form of ruins, chaityas and stupas Andhra Pradesh is also known as the land of the world-famous diamond Koh-i-Noor and many other global known diamonds due to their presence in its Kollur Mine once. It is also known as the "rice bowl of India" for being a major producer of rice in India. Its official language is Telugu; one of the classical languages of India, the fourth most spoken language in India and the 11th-most spoken language in the world.`,
    maplink:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/IN-AP.svg/250px-IN-AP.svg.png",
    subtopics: [
      "Symbols of Andhra-pradesh",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613406463/Andhrap_znmffn.png",
  },
  {
    name: "Assam",
    id: "2",
    details:
      "Assam is a state in northeastern India known for its wildlife, archeological sites and tea plantations. In the west, Guwahati, Assam’s largest city, features silk bazaars and the hilltop Kamakhya Temple. Umananda Temple sits on Peacock Island in the Brahmaputra river.The state capital, Dispur, is a suburb of Guwahati. The ancient pilgrimage site of Hajo and Madan Kamdev, the ruins of a temple complex, lie nearby.  ",
    maplink:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/IN-AS.svg/250px-IN-AS.svg.png",
    subtopics: [
      "Symbols of Assam",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613406293/Assam_yulaay.png",
  },
  {
    name: "Arunachal pradesh",
    id: "3",
    details:
      "Arunachal Pradesh is a state in Northeast India. It borders the states of Assam and Nagaland to the south. It shares international borders with Bhutan in the west, Myanmar in the east, and a disputed border with China in the north at the McMahon Line. Itanagar is the state capital of Arunachal Pradesh. Arunachal Pradesh is the largest of the Seven Sister States of Northeast India by area. Arunachal Pradesh shares 1,129 km border with China's Tibet Autonomous Region.",
      maplink:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/IN-AR.svg/800px-IN-AR.svg.png",
      subtopics: [
      "Symbols of Arunachal pradesh",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613406507/Arunachalp_cnde5q.png",
  },
  {
    name: "Bihar",
    id: "4",
    details:
      "Bihar is a state in East India, bordering Nepal. It is the third-largest state by population and twelfth-largest by territory, with an area of 94,163 km2 (36,357 sq mi). It is contiguous with Uttar Pradesh to its west, Nepal to the north, the northern part of West Bengal to the east, and with Jharkhand to the south.It is divided by the River Ganges, which floods its fertile plains. Important Buddhist pilgrimage sites include the Bodhi Tree in Bodhgaya's Mahabodhi Temple, under which the Buddha allegedly meditated. In the state capital Patna, Mahavir Mandir temple is revered by Hindus, while Sikhs worship at the domed, riverside Gurdwara of Takht Sri Harmandir Sahib Ji. ",
    maplink:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/IN-BR.svg/800px-IN-BR.svg.png",
    subtopics: [
      "Symbols of Bihar",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613406521/bihar_w2bduy.png",
  },
  {
    name: "Chhattisgarh",
    id: "5",
    details:"Chhattisgarh is a heavily forested state in central India known for its temples and waterfalls. Near the capital Raipur, the town of Sirpur on the Mahanadi River is home to the red-brick Lakshmana (Laxman) Temple, decorated with carvings from Indian mythology. In the south, the city of Jagdalpur hosts the Sanjay Market on Sundays, a bartering place for local tribes. The huge Chitrakoot Falls lie to the northwest. ",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/IN-CT.svg/250px-IN-CT.svg.png",
    subtopics: [
      "Symbols of Chhattisgarh",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613409684/Chattisgarh_odps2p.png",},
  
   { name: "Goa",
    id: "6",
    details:"Goa is a state in western India with coastlines stretching along the Arabian Sea. Its long history as a Portuguese colony prior to 1961 is evident in its preserved 17th-century churches and the area’s tropical spice plantations. Goa is also known for its beaches, ranging from popular stretches at Baga and Palolem to those in laid-back fishing villages such as Agonda.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/IN-GA.svg/250px-IN-GA.svg.png",
    subtopics: [
      "Symbols of Bihar",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613409560/goa_z6sjj5.png",},
    
   { name: "Gujarat",
    id: "7",
    details:"Gujarat is a state on the western coast of India with a coastline of 1,600 km (990 mi) – most of which lies on the Kathiawar peninsula – and a population of 60.4 million. It is the fifth-largest Indian state by area and the ninth-largest state by population. Gujarat is bordered by Rajasthan to the northeast, Dadra and Nagar Haveli and Daman and Diu to the south, Maharashtra to the southeast, Madhya Pradesh to the east, and the Arabian Sea and the Pakistani province of Sindh to the west. Its capital city is Gandhinagar, while its largest city is Ahmedabad.The Gujarati people of India are indigenous to the state, and their language Gujarati, is the state's official language. The economy of Gujarat is the fifth-largest in India, with a gross state domestic product (GSDP) of ₹15.03 trillion (US$210 billion) and has the country's 11th-highest GSDP per capita of ₹196,000 (US$2,700).Gujarat ranks 21st among Indian states in human development index.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/IN-GJ.svg/250px-IN-GJ.svg.png",
    subtopics: [
      "Symbols of Gujrat",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613409549/gujrat_o5si9a.png",},
  
    {name: "Haryana",
    id: "8",
    details:"Haryana is a North Indian state surrounding New Delhi on 3 sides. The Yamuna River runs along its eastern border with Uttar Pradesh. Shared with Punjab, the state capital Chandigarh is known for its modernist buildings and gridlike street plan designed by Swiss architect, Le Corbusier. The Zakir Hussain Rose Garden features 1,600 species, while its Rock Garden showcases sculptures made with recycled materials.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/IN-HR.svg/250px-IN-HR.svg.png",
    subtopics: [
      "Symbols of Haryana",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613409512/haryana_urwiwa.png",},
  
   { name: "Himachal Pradesh",
    id: "9",
    details:"Himachal Pradesh is a northern Indian state in the Himalayas. It's home to scenic mountain towns and resorts such as Dalhousie. Host to the Dalai Lama, Himachal Pradesh has a strong Tibetan presence. This is reflected in its Buddhist temples and monasteries, as well as its vibrant Tibetan New Year celebrations. The region is also well known for its trekking, climbing and skiing areas.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/IN-HP.svg/250px-IN-HP.svg.png",
    subtopics: [
      "Symbols of Himachal Pradesh",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613408638/Hp_jdnn0j.png",},
  {
    name: "Jharkhand",
    id: "10",
    details:"Jharkhand is a state in eastern India. It's known for its waterfalls, the elegant Jain temples of Parasnath Hill and the elephants and tigers of Betla National Park. The state capital of Ranchi is a gateway to the park. It features the 17th-century Jagannath Temple, a Hindu shrine and the Jharkhand War Memorial. Tagore Hill is a monument honoring Nobel Prize-winning author Rabindranath Tagore.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/IN-JH.svg/250px-IN-JH.svg.png",
    subtopics: [
      "Symbols of Jharkhand",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613408630/jharkhand_z3za8v.png",},
  {
    name: "Karnataka",
    id: "11",
    details:"Karnataka is a state in southwest India with Arabian Sea coastlines. The capital, Bengaluru (formerly Bangalore), is a high-tech hub known for its shopping and nightlife. To the southwest, Mysore is home to lavish temples including Mysore Palace, former seat of the region’s maharajas. Hampi, once the medieval Vijayanagara empire’s capital, contains ruins of Hindu temples, elephant stables and a stone chariot.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/IN-KA.svg/250px-IN-KA.svg.png",
    subtopics: [
      "Symbols of Karnataka",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613408621/karnataka_datwta.png",},
  {
    name: "Kerala",
    id: "12",
    details:"Kerala, a state on India's tropical Malabar Coast, has nearly 600km of Arabian Sea shoreline. It's known for its palm-lined beaches and backwaters, a network of canals. Inland are the Western Ghats, mountains whose slopes support tea, coffee and spice plantations as well as wildlife. National parks like Eravikulam and Periyar, plus Wayanad and other sanctuaries, are home to elephants, langur monkeys and tigers. ",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/IN-KL.svg/250px-IN-KL.svg.png",
    subtopics: [
      "Symbols of Kerala",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613409723/kerala_slqp1g.png",},
  {
    name: "Madhya Pradesh",
    id: "13",
    details:"Madhya Pradesh, a large state in central India, retains landmarks from eras throughout Indian history. Begun in the 10th century, its Hindu and Jain temples at Khajuraho are renowned for their carvings of erotic scenes, most prominently Kandariya Mahadeva, a temple with more than 800 sculptures. The eastern Bandhavgarh and Kanha national parks, noted Bengal tiger sanctuaries, offer guided safaris. ",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/IN-MP.svg/250px-IN-MP.svg.png",
    subtopics: [
      "Symbols of Madhya Pradesh",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613411784/madhyapradesh_qygpy7.png",},
  {
    name: "Maharashtra",
    id: "14",
    details:"Maharashtra is a state in the western peninsular region of India occupying a substantial portion of the Deccan Plateau. Maharashtra is the second-most populous state in India as well as the second-most populous country subdivision. It was formed on 1 May 1960 by splitting the bilingual Bombay State, which had existed since 1956, into majority Marathi-speaking Maharashtra and Gujarati-speaking Gujarat. The state capital is Mumbai, the most populous urban area in India. The Godavari and the Krishna are the two major rivers in the state. Marathi is the most widely spoken language and is also the official language of the state.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/IN-MH.svg/250px-IN-MH.svg.png",
    subtopics: [
      "Symbols of Maharashtra",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613411793/maharashtra_llbu5w.png",},
  {
    name: "Manipur",
    id: "15",
    details:"Manipur is a state in northeastern India, with the city of Imphal as its capital. It is bounded by the Indian states of Nagaland to the north, Mizoram to the south and Assam to the west. It also borders two regions of Myanmar, Sagaing Region to the east and Chin State to the south.The state covers an area of 22,327 square kilometres (8,621 sq mi) and has a population of almost 3 million, including the Meitei, who are the majority group in the state, the Meitei Pangals (Manipuri Muslims), Naga tribes, Kuki/Zo tribes and other communities, who speak a variety of Sino-Tibetan languages.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/IN-MN.svg/250px-IN-MN.svg.png",
    subtopics: [
      "Symbols of Manipur",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613411800/manipur_jfzg5g.png",},
  {
    name: "Meghalaya",
    id: "16",
    details:"Meghalaya is a state in Northeast India. Meghalaya was formed by carving out two districts from the state of Assam: the United Khasi Hills and Jaintia Hills, and the Garo Hills on 21 January 1972. The population of Meghalaya as of 2016 is estimated to be 3,211,474.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/IN-ML.svg/250px-IN-ML.svg.png",
    subtopics: [
      "Symbols of Meghalaya",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613411815/meghalaya_g4ohha.png",},
  {
    name: "Mizoram",
    id: "17",
    details:`Mizoram is a state in northeastern India, with Aizawl as its seat of government and capital city. The name of the state is derived from "Mizo", the self described name of the native inhabitants, and "Ram", which in the Mizo language means "land." Thus "Mizo-ram" means "land of the Mizos".`,
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/IN-MZ.svg/250px-IN-MZ.svg.png",
    subtopics: [
      "Symbols of Mizoram",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613411821/mizoram_lvlkyc.png",},
  {
    name: "Nagaland",
    id: "18",
    details:"Nagaland is a mountainous state in northeast India, bordering Myanmar. It's home to diverse indigenous tribes, with festivals and markets celebrating the different tribes' culture. Its capital city of Kohima suffered heavy fighting in World War II, commemorated by memorials at the Kohima War Cemetery. The Nagaland State Museum exhibits ancient weaponry, a ceremonial drum and other traditional Naga cultural artifacts.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/IN-NL.svg/250px-IN-NL.svg.png",
    subtopics: [
      "Symbols of Nagaland",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613411829/nagaland_lqrh0w.png",},
  {
    name: "Odisha",
    id: "19",
    details:"Odisha (formerly Orissa), an eastern Indian state on the Bay of Bengal, is known for its tribal cultures and its many ancient Hindu temples. The capital, Bhubaneswar, is home to hundreds of temples, notably the intricately-carved Mukteshvara. The Lingaraj Temple complex, dating to the 11th century, is set around sacred Bindusagar Lake. The Odisha State Museum is focused on the area’s history and environment.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/IN-OR.svg/250px-IN-OR.svg.png",
    subtopics: [
      "Symbols of Odisha",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613411744/odisha_hulbjb.png",},
  {
    name: "Punjab",
    id: "20",
    details:"Punjab, a state bordering Pakistan, is the heart of India’s Sikh community. The city of Amritsar, founded in the 1570s by Sikh Guru Ram Das, is the site of Harmandir Sahib, the holiest gurdwara (Sikh place of worship). Known in English as the Golden Temple, and surrounded by the Pool of Nectar, it's a major pilgrimage site. Also in Amritsar is Durgiana Temple, a Hindu shrine famed for its engraved silver doors.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/IN-PB.svg/250px-IN-PB.svg.png",
    subtopics: [
      "Symbols of Punjab",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613411751/punjab_ki3yib.png",},
  {
    name: "Rajasthan",
    id: "21",
    details:"Rajasthan is a state in northern India. The state covers an area of 342,239 square kilometres or 10.4 percent of the total geographical area of India. It is the largest Indian state by area and the seventh largest by population. ",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/IN-RJ.svg/250px-IN-RJ.svg.png",
    subtopics: [
      "Symbols of Rajasthan",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613411760/rajasthan_mhufh2.png",},
  {
    name: "Sikkim",
    id: "22",
    details:"Sikkim is a state in northeast India, bordered by Bhutan, Tibet and Nepal. Part of the Himalayas, the area has a dramatic landscape that includes India’s highest mountain, 8,586m Kangchenjunga. Sikkim is also home to glaciers, alpine meadows and thousands of varieties of wildflowers. Steep paths lead to hilltop Buddhist monasteries such as Pemayangtse, which dates to the early 1700s.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/IN-SK.svg/250px-IN-SK.svg.png",
    subtopics: [
      "Symbols of Sikkim",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613411885/sikkim_uyzigc.png",},
  {
    name: "Tamil Nadu",
    id: "23",
    details:"Tamil Nadu, a South Indian state, is famed for its Dravidian-style Hindu temples. In Madurai, Meenakshi Amman Temple has high ‘gopuram’ towers ornamented with colourful figures. On Pamban Island, Ramanathaswamy Temple is a pilgrimage site. The town of Kanyakumari, at India’s southernmost tip, is the site of ritual sunrises. Capital Chennai is known for beaches and landmarks including 1644 colonial Fort St. George. ",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/IN-TN.svg/250px-IN-TN.svg.png",
    subtopics: [
      "Symbols of Tamil Nadu",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613411896/tamilnadu_v8mvt1.png",},
  {
    name: "Telangana",
    id: "24",
    details:"Telangana is a state in southern India. In the capital of Hyderabad, the Charminar is a 16th-century mosque with 4 arches supporting 4 towering minarets. The monument overlooks the city's long-running Laad Bazaar. Once the seat of the Qutb Shahi dynasty, the sprawling Golconda Fort is a former diamond-trading center. In the city of Warangal, the centuries-old Warangal Fort features carved stone towers and gateways",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/IN-TG.svg/250px-IN-TG.svg.png",
    subtopics: [
      "Symbols of Telangana",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613411904/telangana_b9djsh.png",},
  {
    name: "Tripura",
    id: "25",
    details:"Tripura is a hilly state in northeast India, bordered on 3 sides by Bangladesh, and home to a diverse mix of tribal cultures and religious groups. In the capital Agartala, the imposing Ujjayanta Palace is set among Mughal gardens, and Gedu Mia’s Mosque has white marble domes and towers. South of the city, Neermahal summer palace sits in the middle of Lake Rudrasagar and blends Hindu and Islamic architectural styles.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/IN-TR.svg/250px-IN-TR.svg.png",
    subtopics: [
      "Symbols of Tripura",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613411937/tripura_su7njr.png",},
  {
    name: "Uttar Pradesh",
    id: "26",
    details:"Uttar Pradesh is a state in northern India. With roughly 200 million inhabitants, it is the most-populous state in India as well as the most-populous country subdivision in the world.The two major rivers of the state, the Ganges and Yamuna, join at Triveni Sangam in Allahabad and flow further east as Ganges. Other prominent rivers are Gomti and Saryu. The forest cover in the state is 6.09% of the state's geographical area.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/IN-UP.svg/250px-IN-UP.svg.png",
    subtopics: [
      "Symbols of Uttar Pradesh",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613411931/up_p0ppjl.png",},
  {
    name: "Uttarakhand",
    id: "27",
    details:"Uttarakhand, a state in northern India crossed by the Himalayas, is known for its Hindu pilgrimage sites. Rishikesh, a major centre for yoga study, was made famous by the Beatles’ 1968 visit. The city hosts the evening Ganga Aarti, a spiritual gathering on the sacred Ganges River. The state's forested Jim Corbett National Park shelters Bengal tigers and other native wildlife.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/IN-UT.svg/250px-IN-UT.svg.png",
    subtopics: [
      "Symbols of Uttarakhand",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613411926/uttarakhand_lf7sos.png",},
  {
    name: "West Bengal",
    id: "28",
    details:"West Bengal is a state in eastern India, between the Himalayas and the Bay of Bengal. Its capital, Kolkata (formerly Calcutta), retains architectural and cultural remnants of its past as an East India Company trading post and capital of the British Raj. The city's colonial landmarks include the government buildings around B.B.D. Bagh Square, and the iconic Victoria Memorial, dedicated to Britain's queen.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/IN-WB.svg/250px-IN-WB.svg.png",
    subtopics: [
      "Symbols of West Bengal",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613411946/westbengal_n3ehdo.png",},
  {
    name: "Andaman and Nicobar Islands",
    id: "29",
    details:"The Andaman Islands are an Indian archipelago in the Bay of Bengal. These roughly 300 islands are known for their palm-lined, white-sand beaches, mangroves and tropical rainforests. Coral reefs supporting marine life such as sharks and rays make for popular diving and snorkeling sites. Indigenous Andaman Islanders inhabit the more remote islands, many of which are off limits to visitors.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/IN-AN.svg/250px-IN-AN.svg.png",
    subtopics: [
      "Symbols of Andaman and Nicobar Islands",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613411953/andaman_rkmmvf.png",},
  {
    name: "Chandigarh",
    id: "30",
    details:"Chandigarh, the capital of the northern Indian states of Punjab and Haryana, was designed by the Swiss-French modernist architect, Le Corbusier. His buildings include the Capitol Complex with its High Court, Secretariat and Legislative Assembly, as well as the giant Open Hand Monument. The nearby Rock Garden is a park featuring sculptures made of stones, recycled ceramics and industrial relics.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/IN-CH.svg/250px-IN-CH.svg.png",
    subtopics: [
      "Symbols of Chandigarh",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613413971/chandigarh_usvtdx.png",},
  {
    name: "Dadra & Nagar Haveli and Daman & Diu",
    id: "31",
    details:"Dadra and Nagar Haveli is a district of the Indian union territory of Dadra and Nagar Haveli and Daman and Diu in western India.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/IN-DN.svg/250px-IN-DN.svg.png",
    subtopics: [
      "Symbols of Dadra & Nagar Haveli and Daman & Diu",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613413932/dadar_nagar_iwuzma.png",},
  {
    name: "Delhi",
    id: "32",
    details:"Delhi, India’s capital territory, is a massive metropolitan area in the country’s north. In Old Delhi, a neighborhood dating to the 1600s, stands the imposing Mughal-era Red Fort, a symbol of India, and the sprawling Jama Masjid mosque, whose courtyard accommodates 25,000 people. Nearby is Chandni Chowk, a vibrant bazaar filled with food carts, sweets shops and spice stalls.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/IN-DL.svg/250px-IN-DL.svg.png",
    subtopics: [
      "Symbols of Delhi",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613412040/delhi_lolqnh.png",},
  {
    name: "Jammu and Kashmir",
    id: "33",
    details:"Jammu and Kashmir was a region formerly administered by India as a state from 1954 to 2019, constituting the southern and southeastern portion of the larger Kashmir region, which has been the subject of a dispute between India, Pakistan and China since the mid-20th century",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Kashmir_Region_November_2019.jpg/250px-Kashmir_Region_November_2019.jpg",
    subtopics: [
      "Symbols of Jammu and Kashmir",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613412007/j_k_twxwgy.png",},
  {
    name: "Lakshadweep",
    id: "34",
    details:"Lakshadweep is a tropical archipelago of 36 atolls and coral reefs in the Laccadive Sea, off the coast of Kerala, India. Not all of the islands are inhabited, and only a few are open to visitors (permits required). Kavaratti, one of the more developed islands, is home to dozens of mosques, including the ornately decorated Ujra Mosque, as well as Kavaratti Aquarium, showcasing regional fish, shark and coral species.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/IN-LD.svg/250px-IN-LD.svg.png",
    subtopics: [
      "Symbols of Lakshadweep",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613413938/lakshdweep_rxuneg.png",},
  {
    name: "Puducherry",
    id: "35",
    details:"Pondicherry (or Puducherry), a French colonial settlement in India until 1954, is now a Union Territory town bounded by the southeastern Tamil Nadu state. Its French legacy is preserved in its French Quarter, with tree-lined streets, mustard-colored colonial villas and chic boutiques. A seaside promenade runs along the Bay of Bengal and passes several statues, including a 4m-high Gandhi Memorial.",
    maplink:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Lagekarte_Unionsterritorium_Puducherry.png/250px-Lagekarte_Unionsterritorium_Puducherry.png",
    subtopics: [
      "Symbols of Puducherry",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613412047/puducherry_anzapx.png",},
  {
    name: "Ladakh",
    id: "36",
    details:"Ladakh is a region administered by India as a union territory, and constituting a part of the larger Kashmir region, which has been the subject of dispute between India, Pakistan, and China since 1947.",
    maplink:"https://img.etimg.com/thumb/msid-71868389,width-1200,height-900,imgsize-329300,overlay-economictimes/photo.jpg",
    subtopics: [
      "Symbols of Ladakh",
      "Etymology & HISTORY",
      "Naxal insurgency",
      "Geography",
      "Major Cities",
      "Universities and colleges",
      "Languages & Cultures",
      "Folk Music & Dance",
      "Tribals",
      "Foods G.I tags",
    ],
    religions: "https://res.cloudinary.com/drbizwyf8/image/upload/v1613412019/ladakh_dlybyo.png",}
]
